default:
  data_path: "./data/"
  result_path: './result/'
  batch_size: 128
  weight_decay: 0.001
  lr: 0.001
  patience: 10

  neg_sampling_ratio: 1
  memory_dim: 100
  time_dim: 100
  embedding_dim: 100
  pos_embedding_dim: 100
  dropout: 0.2
  neighbor_sample_size: 10


datasets:
  wikipedia:
    dataset: 'Wikipedia'

  reddit:
    dataset: 'Reddit'

  mooc:
    dataset: 'MOOC'

  lastfm:
    dataset: 'LastFM'

models:
  ptgnn:
    model: 'ptgnn'

  tgnn:
    model: 'tgnn'
