default:
  data_path: "./data/"
  processed_data_path: "./data/processed"
  result_path: './result'
  seed: 2023

datasets:
  wikipedia:
    dataset: 'wikipedia'

  yelp:
    dataset: 'yelp'

models:

  ptgnn:
    model: 'ptgnn'