default:
  data_path: "./data/"
  processed_data_path: "./data/processed"
  result_path: './result'
  seed: 2023

datasets:
  wikipedia:
    dataset: 'wikipedia'

  reddit:
    dataset: 'reddit'

  mooc:
    dataset: 'mooc'
    
  lastfm:
    dataset: 'lastfm'

models:

  ptgnn:
    model: 'ptgnn'