default:
  data_path: "./data/"
  result_path: './result/'
  batch_size: 128
  weight_decay: 0.01
  lr: 0.0001
  patience: 10

  neg_sampling_ratio: 1
  memory_dim: 100
  time_dim: 100
  embedding_dim: 100
  dropout: 0.4
  neighbor_sample_size: 10


datasets:
  wikipedia:
    dataset: 'Wikipedia'

    ptgnn:
      model: 'ptgnn'

    tgnn:
      model: 'tgnn'

  reddit:
    dataset: 'Reddit'

  mooc:
    dataset: 'MOOC'
    ptgnn:
      model: 'ptgnn'
      dropout: 0.6

    tgnn:
      model: 'tgnn'

  lastfm:
    dataset: 'LastFM'
